# TODO: Adjust for your Supabase project (e.g. when using Supabase CLI locally).
# https://supabase.com/docs/guides/cli/config

[api]
enabled = true
port = 54321
schemas = ["public"]
extra_search_path = ["public"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "http://localhost:5173"

[storage]
enabled = true
